### ISSUE TITLE
pix_image freezes PD when loading many files on w32 

### ISSUE THREAD

**Issue by oliverstotz** [umlaeute/Gem#156]
hi,

i attached a patch that demonstrates the freezing of PD when [pix_image] has opened more than ~2048 files (the exact number actually varied on each trial). it doesn't matter whether the files have already been opened or not, the freeze occurs at around 2048. actually it's not really a freeze as the patch keeps playing, but it can't be saved anymore. also all other write operations fail with this error message in the console:

"[full name of patch]: Too many open files"

OS: Windows 7 / 64bit
PD: 0.48.0 (but it also happens with 0.47.1)
GEM: 0.93.3

things i tried but didn't help:

"thread 0/1" message on opening the image
loading tiff instead of jpg
using [pix_buffer_read] or [pix_multiimage] instead of [pix_image]

best

oliver
[Gem_pix_image_crash_181017.zip](https://github.com/umlaeute/Gem/files/1394803/Gem_pix_image_crash_181017.zip)

**Comment by zomoipotoi** [comment]
Hi, I can confirm the behavior: at 2039 pd is no more able to write on file and in console I have "./deathcounter.txt: write failed". Patch is responsive and I can change it but cannot save modifications since pd is throwing error "[full name of patch]: Too many open files" on console. I can close without saving.

OS: Windows 10 / 64 bit
Pd 0.48.0 
GEM: ver: 0.93.3

Hope this helps!

Ciao
Dario

**Comment by umlaeute** [comment]
i *think* this has been fixed a long time ago, e.g. with d5f1537a524b3c48d5037b6e65439f63d031366a.
(another point to get out a new release...)
