### ISSUE TITLE
pix_video aquisition problem

### ISSUE THREAD

**Issue by Yinameah** [umlaeute/Gem#188]
Hello,

I'm trying to use an ip camera stream in pure-data. I'm not entirely sure it's Gem's fault, but I'm stuck here. My setup is the following :
- IP Camera on a local and dedicated network
- Gstreamer gets the rtsp stream and output on a v4l2sink
- which is a v4l2loopback (https://github.com/umlaeute/v4l2loopback)

If I use a gstreamer test pipeline, or even with a file, it works flawlessly.

But with my rtsp pipeline, when pix_video access the loopback device, I get one frame and then it complains about :
` oops, skipping incomplete capture 1384448 of 1382400 bytes` multiple times.

The loopback device can be accessed without problems from VLC or from the xawtv command line tool. So it appears that pix_video is more touchy about something, but I've no idea what.
And what's strange is that I actually have one frame each time I reload the video device. I can even put a `metro 100` above a `device 1` message and almost get a video.

Anyone has a clue about what's going on ?

I use a Purr-data distribution, with GEM: ver: 0.93.git 438dab3 on an archlinux up-to-date. Also a git version of v4l2loopback.
my gstreamer-pipeline
`gst-launch-1.0  rtspsrc location=rtsp://192.168.1.17/user=admin_password=tlJwpbo6_channel=2_stream=0 
latency = 50 ! rtph264depay  ! avdec_h264 ! videoconvert ! tee ! v4l2sink `

**Comment by umlaeute** [comment]
fixed with 3839a066da5e3292d6013ac5195c5457c0219222

also, you should report bugs in Purr Data to the Purr Data issue tracker (the version `0.93.git~438dab3` doesn't relate to any revision found in this repository; either PurrData is patching the sources or they have otherwise tampered with the revisions; in both cases, I cannot really support it; luckily I just happen to know that I fixed this error two weeks ago...)

**Comment by Yinameah** [comment]
Ok, sorry for bothering you. And really, really thank you for this solution.

Keep the good work, it's wonderfull.
