### ISSUE TITLE
gemmacoswindow blank with [pix_film], [pix_video]

### ISSUE THREAD

**Issue by megrimm** [umlaeute/Gem#200]
loads film fine:

[pix_film]: loaded file: /Users/megrimm/Documents/Pd/externals/Gem/examples/04.pix/../data/anim-1.mov with 91 frames (256x256) at 30.000000 fps

but does not render to square so window just blank white with [pix_film], [pix_video]

non pix stuff is just fine 

this is from your recent deken pre-release but also same results from my build this morning.

macOS 10.14.2

**Comment by umlaeute** [comment]
does `[pix_image]` work?
does it work if you revert 427a3d0e61d61e64e76facfa905c120356383bab  ?

**Comment by megrimm** [comment]
no same deal with [pix_image]... blank white square

with:
```
$ git checkout 427a3d0
$ ./configure --without-QuickTime-framework --without-Carbon-framework --with-pd=/Applications/Pd.app/Contents/Resources --with-defaultwindow=gemmacoswindow
```

configure ends with:
`config.status: error: cannot find input file: `devgem.sh.in'`

**Comment by umlaeute** [comment]
two things:
- i made a horrible typo and really meant reverting commit 59c37ae0eba6a82f3d431595554920792983776b (the commit i mentioned was a much older commit=
- with reverting i actually meant undoing that specific commit, rather than resetting *to* that commit:

~~~
git revert 59c37ae0eba6a82f3d431595554920792983776b
make
~~~

**Comment by megrimm** [comment]
just fetched your latest (be40dd2) and all seems to work fine. loads vid, can see image in widow etc.

**Comment by umlaeute** [comment]
hopefully the widow is not offended.
