### ISSUE TITLE
clang: error: unsupported option '-fopenmp'

### ISSUE THREAD

**Issue by yrostudio** [umlaeute/Gem#266]
HI,
i tried a lot of different ./configure but still got the same error during make install.

clang: error: unsupported option '-fopenmp'

i can't find a way to get rid of it. any idea ?

i'm on macos X Mojave 10.14.6, Pd-0.51-1.

thanks

**Comment by umlaeute** [comment]
that's a bug in the brew package of one of the supporting libraries.
it's not something that can be fixed in Gem.

to get a build, you only have to disable the usage of this library (or don't install it in the first place).
unfortunately i have forgotten which supporting libraries this is.

i would do something like:

~~~sh
find . -iname makefile -exec grep openmp {} +
~~~

this should give you something similar to this one:
~~~make
PKG_MAGICKCORE_CFLAGS = -fopenmp -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -I/usr/include/x86_64-linux-gnu//ImageMagick-6 -I/usr/include/ImageMagick-6
~~~

the above example indicates, that it's the MagickCore library (from imagemagick) that adds the `-fopenmp` flag to the build-process.
try disabling (or uninstalling) it, re-run configure and build.
rinse and repeat till you fixed all libraries that insist on being build with that flag.

**Comment by yrostudio** [comment]
Thanks a lot. it worked.
I’m going to try blackmagic (decklink) drivers now :)

**Comment by kubriel** [comment]
be sure that your video input is YUV #265 
otherwise you get garbled or white image. i think.
