### ISSUE TITLE
[pix_artoolkit]: cannot handle RGBA image

### ISSUE THREAD

**Issue by kubriel** [umlaeute/Gem#269]
as title says
there is [pix_rgba] in pix_artoolkit-help.pd example, but console prints
[pix_artoolkit]: cannot handle RGBA image

i tried to convert video to yuv and grey with [pix_yuv][pix_grey], with same result
[pix_artoolkit]: cannot handle YUV image
[pix_artoolkit]: cannot handle Grey image

fresh gem from git, and fresh artoolkit from https://github.com/artoolkitx/artoolkit5

**Comment by umlaeute** [comment]
i'm pretty sure that `[pix_artoolkit]` is not up to handle the latest artoolkit.
so most likely, a supported version of artoolkit was not detected during compilation and consequently `[pix_artoolkit]` was compiled without artoolkit support - making it effectively a no-op object.

you should have gotten an error `compiled without ARToolKit support!` when instantiating an object.

**Comment by umlaeute** [comment]
otoh, i just noticed the same with `gem` and `pix_fiducialtrack` (sic!) as packaged in Debian.
this indicates a problem with cross-dylib inheritance.

is the `[pix_fiducialtrack]` in #270 from the same build?

**Comment by umlaeute** [comment]
ah no. sorry about the `[pix_fiducialtrack]` noise: *that* object only handles Greyscale images.

**Comment by umlaeute** [comment]
@kubriel could you please post the content of `extra/pix_artoolkit/config.h`?

anyhow, i checked myself and noticed:
- the `./configure` of `[pix_artoolkit]` is somewhat broken, as it doesn't add the relevant compiler/linker flags (as passed with  `--with-artoolkit-*FLAGS=`)
- after fixing configure, the objects simply fails to build
  - some build-failures are due to internal code changes (e.g. the `GEM_RGBA` value) and are trivial to fix
  - other build-failures indicate that ARToolKit has changed in an incompatible way

so to conclude:
- nobody has really built `[pix_artoolkit]` for years
- it would require an effort to port to the new ARToolKit5 SDK
- the binary you somehow managed to build does *not really* have ARToolKit support
  - providing the `--with-artoolkit` flag just enabled enough of the build system to create the binary
  - but configure also detected that it couldn't really use the SDK, so it disabled virtually all of the object's functionality (including the image handler)

**Comment by umlaeute** [comment]
btw, you should have gotten a line saying:
> compiled without ARToolKit support!

when the object gets created (did you miss it, or did it not show up?)

**Comment by kubriel** [comment]
@umlaeute i dont have extra/pix_artoolkit/config.h anymore, as i reinstalled this machine by the time.
