### ISSUE TITLE
[gemwin] with [gemglutwindow] freezes when render

### ISSUE THREAD

**Issue by H-MLim** [umlaeute/Gem#292]
this has happened on Pd ver.0.52-1. the whole Pd freezes when render the [gemwin] with [gemglutwindow] (no problems on just creating window). I didn't experience this on my previous Mac but what would be problem? [gemmacoswindow] and [gemglfw3window] still makes the same problem (#257 and #285) and other choosable windows were cannot be used nor recognized. as sams as before, on Mac Monterey 12.1, Apple M1 Pro.

**Comment by umlaeute** [comment]
> this has happened on Pd ver.0.52-1 [...] on Mac Monterey 12.1, Apple M1 Pro.

is Pd running as `x86_64` (via Rosetta), or natively as `arm64` (using the Gem from https://github.com/umlaeute/Gem/issues/257#issuecomment-1055351656)?

**Comment by H-MLim** [comment]
I believe it's on arm64

**Comment by umlaeute** [comment]
now that i have access to an M1 machine, i've done some more tests:

| window |  CPU | note | status |
|---|---|---|---|
| `[gemglutwindow]` | `arm64` | works (no) freezes with a simple test patch | :green_apple: 
| `[gemglutwindow]` | `amd64` (rosetta) | works (no) freezes with a simple test patch | :green_apple: 
| `[gemglfw3window]` | `arm64` | works (no) freezes with a simple test patch | :green_apple: 
| `[gemglfw3window]` | `amd64` (rosetta) | works (no) freezes with a simple test patch | :green_apple: 
| `[gemcocoawindow]` | `arm64` | **failed to init GLEW**  | :boom:
| `[gemcocoawindow]` | `amd64` (rosetta) |  **failed to init GLEW**  | :boom:
| `[gemmacoswindow]` | `arm64` | **failed to init GLEW**  | :boom:
| `[gemmacoswindow]` | `amd64` (rosetta) |  **failed to init GLEW** | :boom:



System:
| type | name |
|---|---|
| hardware | Mac Studio 2022 (Apple M1 Max) |
| OS | macOS 13.6.1 - Ventura |
| Pd | 0.54-1 |
| Gem | git 551e7b2dc  (0.94-747-g551e7b2dc) |

could it be a problem with your patch (e.g. because it uses more complicated things than mine?)

**Comment by H-MLim** [comment]
unfortunately I don't use Mac so I can't test it anymore. but I believe it could be fine if you are also fine. now I'm back to Windows and still confronting several problems like #262.... btw I'll close this.
