### ISSUE TITLE
Help patches have light-colored canvases behind text boxes

### ISSUE THREAD

**Issue by jamshark70** [umlaeute/Gem#308]
Potentially an odd question, but... is there a reason why Gem help patches place a light-colored canvas behind every comment box?

Here is a representative Gem help patch in pdnext, with a dark color theme.

![pd-gemhelp-canvas](https://user-images.githubusercontent.com/318301/196616175-b0ad03ea-4a94-4a3f-b5ca-090425bc17b9.png)

Pd vanilla help patches do not have this issue, because they don't override the theme's background and text colors.

Now, I can anticipate a response along the lines of not promising usable behavior outside of "standard" Pd ("you're using pdnext at your own risk, if you don't like it, use the official fork"). To that, I have two comments: 1. The light colored canvases don't seem to be doing anything useful, so, per Occam's Razor, it seems unnecessary effort to have put them in; and 2. It isn't really Gem's business to enforce a light-background appearance. (In my case, my optometrist has recently prescribed lenses with a prismatic correction. One side effect is that it's increasingly unpleasant to read dark text on a light background, on an LCD screen. I switched to pdnext + seb's color theme plugin for this reason. Gem help is the only component I've encountered that does not play nicely with this.)

(The other question then would be, if there's no reason for this, then who will do the work of taking them out? In which case, I guess I'd have to volunteer for some of that. Maybe it could be scripted.)

**Comment by 60-hz** [comment]
I am also using pd-next with a color theme, but since I am using black comments and cords, it's still readable on any cases. As you can see on those comparisons, the canvases are making things clear on the screen. It should be very easy to modify the color or even remove canvases from all -help files iteratively using a simple text editor like sublime.
<img width="710" alt="Capture d’écran 2022-10-19 à 11 04 48" src="https://user-images.githubusercontent.com/5449719/196649946-9b016236-a088-4ecb-b771-e18c38f6a422.png">
<img width="710" alt="Capture d’écran 2022-10-19 à 11 09 02" src="https://user-images.githubusercontent.com/5449719/196649965-00990725-9393-4392-8a57-2a011f0c8ec2.png">

**Comment by jamshark70** [comment]
I thought about it some more and I'll close this, as it isn't really Gem's problem. (Well, I'm still not sure why those canvases have to be there but anyway.)

The *real* solution would be for pd to adopt palettes. As long as colors are hardcoded as hex RGB in patch files, there's no reliable way that an algorithm could automatically choose correct colors for different schemes. It would be better if patch files could reference named color labels, but it seems unlikely that this will be done anytime soon.

It's a pity as, for some minority of users, it can be an accessibility issue. But, volunteer dev team, some issues don't make the cut.
