### ISSUE TITLE
[pix_texture] argument

### ISSUE THREAD

**Issue by 60-hz** [umlaeute/Gem#312]
Since [pix_texture] need to be set as "rectangle 0/1" often and it have currently no arguments, it could be really handy to support a "rectangle mode" argument.

**Comment by umlaeute** [comment]
hmm, you shouldn't need to set `[rectangle $1(` **often**.

why don't the defaults work for you?

**Comment by 60-hz** [comment]
Yes, actually the default mode works for all gem primitive shapes.
As soon as I use [model], I need to use mode 0 (TEXTURE_2D) to see the texture.
Also with some shaders, we need to change the rectangle mode.

Using many arguments is always more handy than using many [loadbang] and messages for all parameters, it reduce the pain of patching numerous boxes, at least for the more used ones.

**Comment by umlaeute** [comment]
i think i got a better solution.
instead of adding arbitrary arguments, you can now add init-messages to each Gem object (well, currently to each built-in; abstractions are to follow...).
so rather than doing `[pix_texture 1]` (and later complain that you also want a message to set the initial `quality`), you can now do `[pix_texture; rectangle 1]` (and later do `[pix_texture; rectangle 1; quality 0]`). Pd will add a linebreak before the semicolon, so you really get patches like this, which i think is pretty neat:

![argmessages](https://user-images.githubusercontent.com/214034/213672393-06344201-bce6-45a1-ab1a-aef6682f8010.png)


these init-messages are separated (from each other; and from the object's arguments) by `;` and can be any message that the object understands.
the object receives them *right after creation*, that is: possibly before any other object exists and definitely before the object is connected to anything.

**Comment by 60-hz** [comment]
This is a fabulous idea, and will greatly accelerate the pd and Gem patching experience!
