### ISSUE TITLE
Gem compilation and shared libraries

### ISSUE THREAD

**Issue by 60-hz** [umlaeute/Gem#313]
Compiling Gem works well on my local apple systems, but as soon as I move files to another computer, linked libraries are missing.
I guess It's an easy extra step to do during configure, but I am not sure how to do it and the Wiki did not help...

```
[/Users/username/Documents/Pd/externals/Gem/Gem.pd_darwin: dlopen(/Users/username/Documents/Pd/externals/Gem/Gem.pd_darwin, 0x000A): Library not loaded: '/usr/local/opt/ftgl/lib/libftgl.2.dylib'
  Referenced from: '/Users/username/Documents/Pd/externals/Gem/Gem.pd_darwin'
  Reason: tried: '/usr/local/opt/ftgl/lib/libftgl.2.dylib' (no such file), '/usr/local/lib/libftgl.2.dylib' (no such file), '/usr/lib/libftgl.2.dylib' (no such file)
/Users/username/Documents/Pd/externals/Gem/Gem.pd_darwin: dlopen(/Users/username/Documents/Pd/externals/Gem/Gem.pd_darwin, 0x000A): Library not loaded: '/usr/local/opt/ftgl/lib/libftgl.2.dylib'
  Referenced from: '/Users/username/Documents/Pd/externals/Gem/Gem.pd_darwin'
  Reason: tried: '/usr/local/opt/ftgl/lib/libftgl.2.dylib' (no such file), '/usr/local/lib/libftgl.2.dylib' (no such file), '/usr/lib/libftgl.2.dylib' (no such file)](url)
```

**Comment by umlaeute** [comment]
>  I guess It's an easy extra step to do during configure, but I am not sure how to do it and the Wiki did not help...

no (that is: I would object to any such patch).
configure is for *building*. your problem is *deploying*.

Gem comes with a `localdeps.macos.sh` script that helps embedding libraries with a distributable directory and which is used by our `[CI]`.

You would basically do:
```sh
./autogen.sh && ./configure && make
make install DESTDIR=$(pwd) libdir=/ extradir=/Gem
find Gem -type f "(" -name "*.pd_darwin" -o -name "*.d_*" -o -name "*.so") -exec .git-ci/localdeps.macos.sh {} +
```

(which will add all required dylibs to the `Gem/` folder an update the rpaths in the binaries accordingly).
After that, you can copy the `Gem/` folder to another machine.

feel free to add this information to the wiki if it is missing.
