### ISSUE TITLE
will [text2d(3d)] support other characters and vertical writing?

### ISSUE THREAD

**Issue by H-MLim** [umlaeute/Gem#319]
usually, `text2d` or `text3d` works perfect. but I wonder if those objects can write, or will be supported for other characters except English alphabet, and vertical writing as well. it would be great as Asian Pd user if this feature would be possible.

**Comment by umlaeute** [comment]
The [text*] objects support the entire Unicode set of characters, so it supports non-English texts just fine (eg my "native" alphabet is non-English as well)

However, they enforce a single font, so the chosen font must have the required glyphs (this is different from eg typical text processing systems, where glyphs that are not available on the chosen font will use fallback fonts)

As for vertical fonts, can't you use linebreaks between each character?
This is a bit clumsy and won't deal with multiple lines ("columns"), but should be a viable workaround

**Comment by umlaeute** [comment]
like so:
![helloworld](https://user-images.githubusercontent.com/214034/201599340-f31aeeea-cb05-4e3c-a688-455776aff59b.png)

**Comment by umlaeute** [comment]
> The `[text*]` objects support the entire Unicode set of characters

that is, Unicode chars that are in the range of 0..65535 (which covers most (all?) east-asian characters).

note, that for the `[string ...(` message, you need a list of unicode-points (rather than utf-8 encoded strings). the `[utf82codenumber]` abstraction (from the "unicode" library available via deken) converts utf-8 encoded bytelists (as output by `[list fromsymbol]`) to a list of unicode-points.

if you just want to display a fixed known text, you can of course do the entire conversion beforehand, and just use something like `[string 20320 10 22909 10 19990 10 30028(`

**Comment by H-MLim** [comment]
ah, this example helped a lot. many thanks!
