### ISSUE TITLE
error in pix_video help file regarding ndi input

### ISSUE THREAD

**Issue by ch-nry** [umlaeute/Gem#322]
The help file of ndi input explain to open a ndi stream with :
open MYMACHINE\ (TestStream)

but the correct message is : 
device MYMACHINE...

The ndi help file could also specify that the correct name to open can be found via the enumarate message.

**Comment by umlaeute** [comment]
> but the correct message is :
> device MYMACHINE...

i'm not sure i really understand with the `...`.

an NDI stream can usually be identified with the string `HOSTNAME (Streamname)` (where `HOSTNAME` is an uppercase version of the self-assigned name of the sending machine - something that typically cannot be easily changed; and `Streamname` is some arbitrary name that is given at creation time)

E.g. consider the following dialog in OBS-Studio:
![ndi@obs](https://user-images.githubusercontent.com/214034/213290619-e4554a3f-cd50-46d6-82f1-cab87b54535b.png)

If I enable the above on my trusted `umlautT` host, the stream will be visible as `UMLAUTT (OBS)`, so I would need `[device UMLAUTT\ (OBS)(` (backslash-escaping the space between the hostname and the streamname.

As you can see on the screenshot, I'm using a 3 year old version of the NDI-SDK. Probably things have changed since then?

> The ndi help file could also specify that the correct name to open can be found via the enumarate message.

that's definitely a good idea.

**Comment by ch-nry** [comment]
The problem is the beginning of the message : open vs device. The rest is fine!!! 
Sorry, I was not clear.

**Comment by umlaeute** [comment]
:facepalm: 

incidentally i was wondering about `open` as well

**Comment by ch-nry** [comment]
all good!
thanks
