### ISSUE TITLE
Anti-alisasing mode under windows

### ISSUE THREAD

**Issue by 60-hz** [umlaeute/Gem#341]
On Windows machines, "FSSA" message has no effect and need to be set (forced or overridden) in the graphic driver settings to be active.

On MacOS machine, it works and is activated by default, which is looking far better.

**Comment by umlaeute** [comment]
the problem is, that three is no standard way to enable FSAA across platforms (at least: last time I checked),
so we are sometimes resorting to hacks:
- `gemglfw3window` here the GLFW3 API offers a standardized interface; if things look different on Windows than on macOS using the glfw3-backend, then this is likely to be a problem of glfw3
- `gemmacwindow`/`gemmacoswindow`: uses some macOS-specific API to enable FSAA by various degrees
- `gemglxwindow` uses an nVidia-specific hack to enable FSAA (that is: it won't work with other VGA-adapters)

personally I think the way to go is to use glfw3 wherever possible (rather than trying to backport whatever GLFW3 does to the various Gem windowing-backends)

**Comment by 60-hz** [comment]
Here is more infos:
On Windows, using gemwin and [gemglfw3window], I can create an anti-aliased gem window with "FSSA 4" message before windows creation... (Using [gemglWin32], I need to force the graphic driver to do so..).

Finally why not using gemglfw3window as default windows manager also on windows? and maybe set a default FSAA to follow same rendering quality of macOS?

The drawbacks are:
- border 0/1 is not implemented
- "fullscreen 1" messages have issues see https://github.com/umlaeute/Gem/issues/343
