### ISSUE TITLE
what's the best environment for video playing?

### ISSUE THREAD

**Issue by H-MLim** [umlaeute/Gem#396]
#262 issue is still continuing on my Windows 11. I have K-Lite Codec Version 18.0.0 Standard, recent Pd(ver.0.54.1), and recent Gem (v.0.94-snapshot Jan.09). and I've made my video as Quicktime Mov or MP4 file. but still my video isn't going so well, both on `pix_film` and `pix_movie`. so how should I encode my video for playing smoothly?

**Comment by umlaeute** [comment]
i'm afraid i do not have an answer for that question.
actually, i doubt that there is an answer at all; and if there was one, it would probably be obsolete by next year.

ideally, such information would be collected by the community at some central place.

**Comment by umlaeute** [comment]
probably some such place could be the [discussions](https://github.com/umlaeute/Gem/discussions).

I have no idea how to motivate other people to partake in that discussion though (but that shouldn't keep you from opening such a discussion).

in any case, i think your problem is already tracked in #262, so I'd like to close *this* issue (as I don't see the point in having multiple tickets tracking the same problem; most importantly, the problem will not be solved any faster by opening more tickets)

**Comment by H-MLim** [comment]
oh OK. then I'll keep try to discuss with other web communities.

**Comment by umlaeute** [comment]
if you do find something useful, please open a [discussions](https://github.com/umlaeute/Gem/discussions) and add that information, so it's easier for others to find :-)
